using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using ZeegZag.Crawler2.Entity;
using ZeegZag.Crawler2.Services.Database;

namespace ZeegZag.Crawler2.Services.Gdax
{
    public class GdaxService : ExchangeServiceBase
    {
        private const string PriceUrl = "https://api.gdax.com/products/{0}-{1}/stats";
        private const string MarketUrl = "https://api.gdax.com/products";
        private const string VolumeUrl = "https://api.gdax.com/products/{0}-{1}/candles?granularity=8";
        

        public override string Name { get; } = "Gdax";

        /// <inheritdoc />
        public override void Init(zeegzagContext db)
        {
            GetExchangeId(db);
            RegisterRateLimit(2);

            CreatePuller(PULLER_CURRENCY, 60 * 60, 0, OnPullingCurrencies); //pull new currencies every 6 hours            
            CreatePuller(PULLER_MARKETS, 60 * 60, 45, OnPullingMarkets); //pull markets every hour            
            CreatePuller(PULLER_PRICE, 60, 90, OnPullingPrices); //pull prices every minute
        }

        private async Task OnPullingPrices()
        {
            using (var db = DatabaseService.CreateContext())
            {
                //get all prices from db
                var prices = db.BorsaCurrencyT
                    .Where(bc => bc.BorsaId == ExchangeId && !bc.Disabled && bc.AutoGenerated != true)
                    .Select(bc => new
                    {
                        Id = bc.Id,
                        FromId = bc.FromCurrencyId,
                        From = bc.FromCurrencyName,
                        ToId = bc.ToCurrencyId,
                        To = bc.ToCurrencyName,
                        Price = bc.Price,
                    }).ToList();
                int i = 0;

                var tasks = new List<Task>(prices.Count);
                foreach (var bc in prices)
                {
                    tasks.Add(Task.Factory.StartNew(() =>
                    {
                        //request last minute and daily ticker

                        var responsePrice = Pull<GdaxTicker>(string.Format(PriceUrl, bc.To, bc.From)).Result;
                        //var responseVolume = Pull<JArray[]>(string.Format(VolumeUrl, bc.To, bc.From)).Result;
                        
                        var job = new PriceUpdaterJob(bc.Id, Convert.ToDecimal(responsePrice.last));
                        //if (responseVolume.Length > 0)
                        //{
                          //  var data = responseVolume[0];
                            //var mv = Convert.ToDecimal(data.Last.Value<string>());
                            var dv = Convert.ToDecimal(responsePrice.volume);
                            var dbv = 0;
                            //job.UpdateVolume(mv, 1);
                            job.UpdateVolume24(dv, dbv);
                        //}
                        //else
                        //{
                        //    Console.WriteLine(string.Format("Could not pull {0}-{1} volume from {2}: List was empty",
                        //        bc.To, bc.From, Name));
                        //}

                        DatabaseService.Enqueue(job);
                        DatabaseService.Enqueue(new UsdGeneratorJob(ExchangeId, bc.FromId, bc.ToId, bc.Price));
                    }));
                }
                Task.WaitAll(tasks.ToArray());
            }
        }

        private async Task OnPullingMarkets()
        {
            var response = Pull<List<GdaxMarket>>(MarketUrl).Result;

            using (var db = DatabaseService.CreateContext())
            {
                //get all prices from db
                var prices = db.BorsaCurrencyT
                    .Include(bc => bc.FromCurrency).Include(bc => bc.ToCurrency)
                    .Where(bc => bc.BorsaId == ExchangeId)
                    .ToList();

                //get markets
                foreach (var market in response)
                {
                    var from = market.quote_currency;
                    var to = market.base_currency;

                    new MarketUpdaterJob(ExchangeId, from, to, true, prices).Execute(db);
                }
                new MarketUpdaterJob(prices).Execute(db);

                db.SaveChanges();
            }
        }

        private async Task OnPullingCurrencies()
        {
            var response = Pull<List<GdaxMarket>>(MarketUrl).Result;

            //get coin names
            var coinNames = response.SelectMany(p =>
                {
                    var from = p.quote_currency;
                    var to = p.base_currency;
                return new List<string>() { from, to };
            }).Where(c => !string.IsNullOrEmpty(c))
            .Distinct()
            .ToList();

            foreach (var coin in coinNames)
            {
                DatabaseService.Enqueue(new CurrencyUpdaterJob(
                    ExchangeId,
                    coin,
                    coin,
                    true,
                    null));
            }
        }
        
        
    }
}
