using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ZeegZag.Crawler2.Entity;
using ZeegZag.Crawler2.Services.Database;

namespace ZeegZag.Crawler2.Services.Hitbtc
{
    public class HitbtcService : ExchangeServiceBase
    {
        private const string MarketUrl = "https://api.hitbtc.com/api/2/public/symbol";
        private const string PriceUrl = "https://api.hitbtc.com/api/2/public/ticker";
        private const string VolumeUrl = "https://api.hitbtc.com/api/2/public/candles/{0}?limit=1&period=M1";

        public override string Name { get; } = "Hitbtc";

        /// <inheritdoc />
        public override void Init(zeegzagContext db)
        {
            GetExchangeId(db);
            RegisterRateLimit(20);

            CreatePuller(PULLER_CURRENCY, 60 * 60, 0, OnPullingCurrencies); //pull new currencies every 6 hours            
            CreatePuller(PULLER_MARKETS, 60 * 60, 45, OnPullingMarkets); //pull markets every hour            
            CreatePuller(PULLER_PRICE, 60, 90, OnPullingPrices); //pull prices every minute
        }

        private async Task OnPullingPrices()
        {
            var response = Pull<List<HitbtcTicker>>(PriceUrl).Result;

            using (var db = DatabaseService.CreateContext())
            {
                //get all prices from db
                var prices = db.BorsaCurrencyT
                    .Where(bc => bc.BorsaId == ExchangeId && !bc.Disabled && bc.AutoGenerated != true)
                    .Select(bc => new
                    {
                        Id = bc.Id,
                        FromId = bc.FromCurrencyId,
                        From = bc.FromCurrencyName,
                        ToId = bc.ToCurrencyId,
                        To = bc.ToCurrencyName,
                        Price = bc.Price,
                    }).ToList();

                var tasks = new List<Task>(prices.Count);
                foreach (var bc in prices)
                {
                    tasks.Add(Task.Factory.StartNew(() =>
                    {
                        var key = bc.To + bc.From;
                        var market = response.FirstOrDefault(d => d.symbol == key);
                        if (market != null)
                        {
                            var job = new PriceUpdaterJob(bc.Id, Convert.ToDecimal(market.last))
                                .UpdateVolume24(Convert.ToDecimal(market.volume),
                                    Convert.ToDecimal(market.volumeQuote));

                            //var responseVolume = Pull<List<HitbtcCandle>>(string.Format(VolumeUrl, key)).Result;
                            //if (responseVolume.Count > 0)
                            //    job.UpdateVolume(Convert.ToDecimal(responseVolume[0].volume), 1);
                            DatabaseService.Enqueue(job);
                            DatabaseService.Enqueue(new UsdGeneratorJob(ExchangeId, bc.FromId, bc.ToId, bc.Price));
                        }
                    }));
                }
                Task.WaitAll(tasks.ToArray());
            }
        }
        

        private async Task OnPullingMarkets()
        {
            var response = Pull<List<HitbtcMarket>>(MarketUrl).Result;

            using (var db = DatabaseService.CreateContext())
            {
                //get all prices from db
                var prices = db.BorsaCurrencyT
                    .Include(bc => bc.FromCurrency).Include(bc => bc.ToCurrency)
                    .Where(bc => bc.BorsaId == ExchangeId)
                    .ToList();

                //get markets
                foreach (var market in response)
                {
                    var from = market.quoteCurrency;
                    var to = market.baseCurrency;

                    new MarketUpdaterJob(ExchangeId, from, to, true, prices).Execute(db);
                }
                new MarketUpdaterJob(prices).Execute(db);

                db.SaveChanges();
            }
        }

        private async Task OnPullingCurrencies()
        {
            var response = Pull<List<HitbtcMarket>>(MarketUrl).Result;

            var coinNames = response.SelectMany(p =>
                {
                    var from = p.quoteCurrency;
                    var to = p.baseCurrency;
                    return new List<string>() {from, to};
                }).Distinct()
                .ToList();

            foreach (var currency in coinNames)
                DatabaseService.Enqueue(new CurrencyUpdaterJob(
                    ExchangeId,
                    currency,
                    currency,
                    true,
                    null));
            
        }
    }
}
